import { readFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

export const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");

export async function buildContent(dataSource = "src/data/openfoodfacts.js") {
  const parts = [
    "src/runtime.js",
    "src/core/gtin.js",
    "src/sites/leclerc.js",
    dataSource,
    "src/ui/widget.js",
    "src/main.js",
  ];
  const sources = await Promise.all(parts.map((part) => readFile(resolve(root, part), "utf8")));
  return `// Generated by scripts/build.mjs. Edit files in src/ instead.\n(() => {\n  "use strict";\n\n${sources.map((source) => source.trimEnd()).join("\n\n")}\n})();\n`;
}
