import { readFile, writeFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import { dirname, resolve } from "node:path";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const parts = [
  "src/runtime.js",
  "src/core/gtin.js",
  "src/sites/leclerc.js",
  "src/data/openfoodfacts.js",
  "src/ui/widget.js",
  "src/main.js",
];

const sources = await Promise.all(parts.map((part) => readFile(resolve(root, part), "utf8")));
const output = `// Generated by scripts/build.mjs. Edit files in src/ instead.\n(() => {\n  "use strict";\n\n${sources.map((source) => source.trimEnd()).join("\n\n")}\n})();\n`;
const target = resolve(root, "content.js");
if (process.argv.includes("--check")) {
  const current = await readFile(target, "utf8");
  if (current !== output) {
    console.error("content.js is outdated. Run node scripts/build.mjs.");
    process.exitCode = 1;
  } else {
    console.log("content.js is up to date");
  }
} else {
  await writeFile(target, output);
  console.log("Built content.js from src/");
}
